### ISSUE TITLE
jaxb bindingene for oppslagstjenesten skaper konflikter for de som skal integrere mot kontaktregisteret og digital postkasse

### ISSUE THREAD

**Issue by aberner** [digipost/sdp-shared#3]
se https://github.com/difi/sikker-digital-post-java-klient/issues/23

får feilmeldingen 

```
org.apache.cxf.service.factory.ServiceConstructionException
at org.apache.cxf.jaxb.JAXBDataBinding.initialize(JAXBDataBinding.java:327)
at org.apache.cxf.service.factory.AbstractServiceFactoryBean.initializeDataBindings(AbstractServiceFactoryBean.java:86)
at .........

Caused by: com.sun.xml.bind.v2.runtime.IllegalAnnotationsException: 7 counts of IllegalAnnotationExceptions
Two classes have the same XML type name "{http://begrep.difi.no}reservasjon". Use @XmlType.name and @XmlType.namespace to assign different names to them.
this problem is related to the following location:
at no.difi.begrep.Reservasjon
at protected no.difi.begrep.Reservasjon no.difi.begrep.Person.reservasjon
at no.difi.begrep.Person
at protected java.util.List no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentEndringerRespons.person
at no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentEndringerRespons
this problem is related to the following location:
at no.difi.begrep.DifiReservasjon
at protected no.difi.begrep.DifiReservasjon no.difi.begrep.DifiPerson.reservasjon
at no.difi.begrep.DifiPerson
at public no.difi.begrep.DifiPerson no.difi.begrep.ObjectFactory.createDifiPerson()
at no.difi.begrep.ObjectFactory
Two classes have the same XML type name "{http://begrep.difi.no}status". Use @XmlType.name and @XmlType.namespace to assign different names to them.
this problem is related to the following location:
at no.difi.begrep.Status
at protected no.difi.begrep.Status no.difi.begrep.Person.status
at no.difi.begrep.Person
at protected java.util.List no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentEndringerRespons.person
at no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentEndringerRespons
this problem is related to the following location:
at no.difi.begrep.DifiStatus
at protected no.difi.begrep.DifiStatus no.difi.begrep.DifiPerson.status
at no.difi.begrep.DifiPerson
at public no.difi.begrep.DifiPerson no.difi.begrep.ObjectFactory.createDifiPerson()
at no.difi.begrep.ObjectFactory
Two classes have the same XML type name "{http://begrep.difi.no}Mobiltelefonnummer". Use @XmlType.name and @XmlType.namespace to assign different names to them.
this problem is related to the following location:
at no.difi.begrep.Mobiltelefonnummer
at protected no.difi.begrep.Mobiltelefonnummer no.difi.begrep.Kontaktinformasjon.mobiltelefonnummer
at no.difi.begrep.Kontaktinformasjon
at protected no.difi.begrep.Kontaktinformasjon no.difi.begrep.Person.kontaktinformasjon
at no.difi.begrep.Person
at protected java.util.List no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentEndringerRespons.person
at no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentEndringerRespons
this problem is related to the following location:
at no.difi.begrep.DifiMobiltelefonnummer
at protected no.difi.begrep.DifiMobiltelefonnummer no.difi.begrep.DifiKontaktinformasjon.mobiltelefonnummer
at no.difi.begrep.DifiKontaktinformasjon
at protected no.difi.begrep.DifiKontaktinformasjon no.difi.begrep.DifiPerson.kontaktinformasjon
at no.difi.begrep.DifiPerson
at public no.difi.begrep.DifiPerson no.difi.begrep.ObjectFactory.createDifiPerson()
at no.difi.begrep.ObjectFactory
Two classes have the same XML type name "{http://begrep.difi.no}Epostadresse". Use @XmlType.name and @XmlType.namespace to assign different names to them.
this problem is related to the following location:
at no.difi.begrep.Epostadresse
at protected no.difi.begrep.Epostadresse no.difi.begrep.Kontaktinformasjon.epostadresse
at no.difi.begrep.Kontaktinformasjon
at protected no.difi.begrep.Kontaktinformasjon no.difi.begrep.Person.kontaktinformasjon
at no.difi.begrep.Person
at protected java.util.List no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentEndringerRespons.person
at no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentEndringerRespons
this problem is related to the following location:
at no.difi.begrep.DifiEpostadresse
at protected no.difi.begrep.DifiEpostadresse no.difi.begrep.DifiKontaktinformasjon.epostadresse
at no.difi.begrep.DifiKontaktinformasjon
at protected no.difi.begrep.DifiKontaktinformasjon no.difi.begrep.DifiPerson.kontaktinformasjon
at no.difi.begrep.DifiPerson
at public no.difi.begrep.DifiPerson no.difi.begrep.ObjectFactory.createDifiPerson()
at no.difi.begrep.ObjectFactory
Two classes have the same XML type name "{http://begrep.difi.no}Kontaktinformasjon". Use @XmlType.name and @XmlType.namespace to assign different names to them.
this problem is related to the following location:
at no.difi.begrep.Kontaktinformasjon
at protected no.difi.begrep.Kontaktinformasjon no.difi.begrep.Person.kontaktinformasjon
at no.difi.begrep.Person
at protected java.util.List no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentEndringerRespons.person
at no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentEndringerRespons
this problem is related to the following location:
at no.difi.begrep.DifiKontaktinformasjon
at protected no.difi.begrep.DifiKontaktinformasjon no.difi.begrep.DifiPerson.kontaktinformasjon
at no.difi.begrep.DifiPerson
at public no.difi.begrep.DifiPerson no.difi.begrep.ObjectFactory.createDifiPerson()
at no.difi.begrep.ObjectFactory
Two classes have the same XML type name "{http://begrep.difi.no}SikkerDigitalPostAdresse". Use @XmlType.name and @XmlType.namespace to assign different names to them.
this problem is related to the following location:
at no.difi.begrep.SikkerDigitalPostAdresse
at protected no.difi.begrep.SikkerDigitalPostAdresse no.difi.begrep.Person.sikkerDigitalPostAdresse
at no.difi.begrep.Person
at protected java.util.List no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentEndringerRespons.person
at no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentEndringerRespons
this problem is related to the following location:
at no.difi.begrep.DifiSikkerDigitalPostAdresse
at protected no.difi.begrep.DifiSikkerDigitalPostAdresse no.difi.begrep.DifiPerson.sikkerDigitalPostAdresse
at no.difi.begrep.DifiPerson
at public no.difi.begrep.DifiPerson no.difi.begrep.ObjectFactory.createDifiPerson()
at no.difi.begrep.ObjectFactory
```

Feilen har blitt løst ved å endre følgende fil:
https://github.com/digipost/sdp-shared/blob/master/xsd/src/main/jaxb/bindings.xjb

 jag har bara kommenterat ut føljande:
```

<!--<bindings schemaLocation="../difi-begrepskatalog/xsd/oppslag/oppslagstjeneste-metadata-14-05.xsd" node="/xs:schema">
   <schemaBindings>
      <nameXmlTransform>
         <typeName prefix="Difi" />
         <anonymousTypeName prefix="Difi" />
         <elementName prefix="Difi" />
      </nameXmlTransform>
   </schemaBindings>
</bindings>-->
```

**Comment by landro** [comment]
Fjernet XSD avhengigheten til oppslagstjenesten da den ikke er i bruk i beabaac26d213a607fa4f504db00e69a496e49c7
